### PR TITLE
spellings

### PR DESCRIPTION
**Pull request by devsikander**
minor typo fixes

### CODE REVIEW

**Comment by syntholly** [comment]
Not sure I completely agree with this, however small it is.
It's all near-negligible but `the interesting stuff` is absolutely acceptable in my opinion.

It's _the_ interesting stuff. A collection of it, within.

**Comment by devsikander** [comment]
theorically (instead of theoretically) is a typo.

How about "the most interesting" instead of "the very interesting" ?

**Comment by syntholly** [comment]
I like that! 

Apologies, I didn't see the `theorically` part in the commit. You're dead-on with that.

**Comment by OLEG77BNT** [comment]
Hello. I want to order google recaptcha (de)obfuscation. Can you write your contacts?

**Pull request closed without merging**
